# Configuración SonarQube Cloud para Backend SIG-ARROZ
sonar.projectKey=andresnico44_sig-arroz-backend
sonar.organization=andresnico44

# Excluir archivos estáticos generados automáticamente y librerías externas
sonar.exclusions=staticfiles/**,**/*.html,**/*.css,**/*.js,venv/**,.venv/**
sonar.sources=.
