# Generated by Django 6.0.4 on 2026-05-16 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion_departamento', models.CharField(max_length=100)),
                ('ubicacion_municipio', models.CharField(max_length=100)),
                ('area_total_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fincas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fincas',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area_hectareas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('INACTIVO', 'Inactivo'), ('PREPARACION', 'En Preparación'), ('EJECUCION', 'En Ejecución'), ('COSECHADO', 'Cosechado')], default='INACTIVO', max_length=20)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='arroz.finca')),
            ],
            options={
                'db_table': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='CicloProductivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variedad_arroz', models.CharField(max_length=100)),
                ('fecha_siembra_estimada', models.DateField()),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EJECUCION', 'En Ejecución'), ('COSECHADO', 'Cosechado'), ('FINALIZADO', 'Finalizado')], default='PLANIFICADO', max_length=20)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='arroz.lote')),
            ],
            options={
                'db_table': 'ciclos_productivos',
            },
        ),
        migrations.CreateModel(
            name='AnalisisSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_muestreo', models.DateField()),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('materia_organica_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('textura', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_suelos', to='arroz.lote')),
            ],
            options={
                'db_table': 'analisis_suelos',
            },
        ),
    ]
