# Generated by Django 6.0.5 on 2026-05-17 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arroz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisissuelo',
            name='fosforo_ppm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='analisissuelo',
            name='laboratorio',
            field=models.CharField(default='Laboratorio General', max_length=150),
        ),
        migrations.AddField(
            model_name='analisissuelo',
            name='potasio_meq',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='cicloproductivo',
            name='anio',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='cicloproductivo',
            name='fecha_cosecha_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cicloproductivo',
            name='fecha_fin_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cicloproductivo',
            name='fecha_macollamiento_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cicloproductivo',
            name='fecha_panicula_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cicloproductivo',
            name='fecha_preparacion_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cicloproductivo',
            name='nombre_ciclo',
            field=models.CharField(default='Ciclo sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='cicloproductivo',
            name='semestre',
            field=models.CharField(choices=[('1', 'Primer Semestre (A)'), ('2', 'Segundo Semestre (B)')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='lote',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='sistema_produccion',
            field=models.CharField(choices=[('RIEGO', 'Riego'), ('SECANO', 'Secano')], default='RIEGO', max_length=20),
        ),
        migrations.AddField(
            model_name='lote',
            name='tipo_suelo',
            field=models.CharField(choices=[('ARCILLOSO', 'Arcilloso'), ('FRANCO', 'Franco'), ('ARENOSO', 'Arenoso')], default='FRANCO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cicloproductivo',
            name='fecha_siembra_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PREPARACION', 'En Preparación'), ('EN_CICLO', 'En Ciclo'), ('COSECHADO', 'Cosechado'), ('DESCANSO', 'En Descanso')], default='ACTIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PRODUCTOR', 'Productor'), ('TECNICO', 'Técnico')], default='TECNICO', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
    ]
