# Generated by Django 6.0.5 on 2026-05-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arroz', '0002_analisissuelo_fosforo_ppm_analisissuelo_laboratorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('labor', models.CharField(choices=[('RASTRA', 'Pase de Rastra'), ('PULIDOR', 'Pase de Pulidor'), ('CABALLONEO', 'Caballoneo'), ('NIVELACION', 'Nivelación (Laser/Taipa)'), ('ZANJEO', 'Zanjeo/Drenajes'), ('OTRO', 'Otro')], max_length=20)),
                ('horas_maquina', models.DecimalField(decimal_places=2, help_text='Horas de uso del tractor', max_digits=5)),
                ('combustible_galones', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones', to='arroz.cicloproductivo')),
            ],
            options={
                'db_table': 'preparacion_maquinaria',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoFenologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fase', models.CharField(choices=[('GERMINACION', 'Germinación / Emergencia'), ('PLANTULA', 'Plántula'), ('MACOLLAMIENTO', 'Macollamiento (Inicio/Máximo)'), ('PRIMORDIO', 'Diferenciación de Primordio Floral'), ('EMBUCHAMIENTO', 'Embuchamiento'), ('FLORACION', 'Floración (Antesis)'), ('GRANO_LECHOSO', 'Grano Lechoso'), ('GRANO_PASTOSO', 'Grano Pastoso'), ('MADUREZ_COSECHA', 'Madurez de Cosecha')], max_length=30)),
                ('dias_transcurridos_calculados', models.IntegerField(blank=True, help_text='Días transcurridos desde la siembra (auto calculado)', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fenologia/')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_fenologicos', to='arroz.cicloproductivo')),
            ],
            options={
                'db_table': 'seguimiento_fenologico',
            },
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(choices=[('VOLEO', 'Al Voleo'), ('MECANIZADA', 'Sembradora Mecanizada'), ('TRANSPLANTE', 'Transplante')], default='VOLEO', max_length=20)),
                ('variedad', models.CharField(max_length=100)),
                ('dosis_kg_ha', models.DecimalField(decimal_places=2, help_text='Kilogramos de semilla por Hectárea', max_digits=5)),
                ('tratamiento_semilla', models.CharField(blank=True, help_text='Fungicidas o insecticidas aplicados a la semilla', max_length=150, null=True)),
                ('germinacion_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ciclo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siembra', to='arroz.cicloproductivo')),
            ],
            options={
                'db_table': 'siembra',
            },
        ),
    ]
