# Generated by Django 6.0.5 on 2026-05-18 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arroz', '0003_preparacionmaquinaria_seguimientofenologico_siembra'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparacionmaquinaria',
            name='costo_hora',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='preparacionmaquinaria',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Fertilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('etapa_fenologica', models.CharField(max_length=50)),
                ('tipo_fertilizante', models.CharField(max_length=100)),
                ('fuente_comercial', models.CharField(max_length=100)),
                ('dosis_kg_ha', models.DecimalField(decimal_places=2, max_digits=7)),
                ('costo_producto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizaciones', to='arroz.cicloproductivo')),
            ],
            options={
                'db_table': 'fertilizacion',
            },
        ),
        migrations.CreateModel(
            name='MonitoreoFitosanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_problema', models.CharField(choices=[('PLAGA', 'Plaga'), ('ENFERMEDAD', 'Enfermedad'), ('MALEZA', 'Maleza')], max_length=20)),
                ('nombre_comun', models.CharField(max_length=150)),
                ('umbral_danio_porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de umbral de daño observado', max_digits=5)),
                ('decision_tecnica', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='arroz.cicloproductivo')),
            ],
            options={
                'db_table': 'monitoreo_fitosanitario',
            },
        ),
        migrations.CreateModel(
            name='AplicacionAgroquimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('ingrediente_activo', models.CharField(max_length=150)),
                ('dosis_por_ha', models.DecimalField(decimal_places=2, max_digits=7)),
                ('equipo_aspersion', models.CharField(max_length=100)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('velocidad_viento_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('periodo_carencia_dias', models.IntegerField(help_text='Días de retiro antes de cosechar')),
                ('costo_producto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_agroquimicos', to='arroz.cicloproductivo')),
                ('monitoreo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones', to='arroz.monitoreofitosanitario')),
            ],
            options={
                'db_table': 'aplicacion_agroquimico',
            },
        ),
        migrations.CreateModel(
            name='RegistroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('MANO_DE_OBRA', 'Mano de Obra'), ('INSUMOS_AGROQUIMICOS', 'Insumos Agroquímicos'), ('MAQUINARIA', 'Maquinaria'), ('ARRENDAMIENTO_TIERRA', 'Arrendamiento de Tierra'), ('TRANSPORTE', 'Transporte'), ('OTROS', 'Otros')], max_length=30)),
                ('descripcion', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='arroz.cicloproductivo')),
            ],
            options={
                'db_table': 'registro_costo',
            },
        ),
        migrations.CreateModel(
            name='RegistroHidrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('volumen_agua_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuente_hidrica', models.CharField(choices=[('CANAL', 'Canal de Riego'), ('RIO', 'Río'), ('POZO', 'Pozo Profundo')], max_length=20)),
                ('costo_bombeo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dias_inundacion', models.IntegerField()),
                ('lamina_agua_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_drenaje', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], max_length=20)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riegos', to='arroz.cicloproductivo')),
            ],
            options={
                'db_table': 'registro_hidrico',
            },
        ),
    ]
