# Generated by Django 6.0.5 on 2026-05-27 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arroz', '0004_preparacionmaquinaria_costo_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('produccion_obtenida_kg', models.DecimalField(decimal_places=2, help_text='Producción total obtenida en Kilogramos', max_digits=12)),
                ('humedad_grano_porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de humedad del grano al corte', max_digits=5)),
                ('impurezas_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de impurezas', max_digits=5)),
                ('condiciones_cosecha', models.TextField(blank=True, help_text='Condiciones generales durante la cosecha (ej. lluvia, acame)', null=True)),
                ('ciclo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cosecha', to='arroz.cicloproductivo')),
            ],
            options={
                'db_table': 'cosecha',
            },
        ),
    ]
