# Generated by Django 6.0.5 on 2026-06-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arroz', '0005_cosecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('humedad_final_porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de humedad final logrado en secamiento', max_digits=5)),
                ('porcentaje_grano_entero', models.DecimalField(decimal_places=2, help_text='Porcentaje de granos enteros logrados en trilla', max_digits=5)),
                ('porcentaje_grano_quebrado', models.DecimalField(decimal_places=2, help_text='Porcentaje de granos quebrados logrados en trilla', max_digits=5)),
                ('precio_tonelada_cop', models.DecimalField(decimal_places=2, help_text='Precio pagado por tonelada en pesos COP', max_digits=12)),
                ('descuentos_aplicados_cop', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuentos aplicados por humedad o impurezas en pesos COP', max_digits=12)),
                ('ingreso_neto_cop', models.DecimalField(decimal_places=2, help_text='Monto neto final recibido del molino en pesos COP', max_digits=12)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales sobre la trilla o liquidación', null=True)),
                ('ciclo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion', to='arroz.cicloproductivo')),
            ],
            options={
                'db_table': 'liquidacion',
            },
        ),
    ]
