# Generated by Django 6.0.5 on 2026-06-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arroz', '0006_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparacionmaquinaria',
            name='condicion_humedad',
            field=models.CharField(choices=[('SECO', 'Suelo Seco'), ('CAPACIDAD_CAMPO', 'Capacidad de Campo (Ideal)'), ('SATURADO', 'Saturado / Lodo')], default='CAPACIDAD_CAMPO', max_length=20),
        ),
    ]
