# Generated by Django 6.0.5 on 2026-06-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arroz', '0007_preparacionmaquinaria_condicion_humedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientofenologico',
            name='estado_general',
            field=models.CharField(choices=[('EXCELENTE', 'Excelente Vigor'), ('BUENO', 'Buen Desarrollo'), ('REGULAR', 'Desarrollo Regular / Atraso'), ('MALO', 'Deficiente / Estrés Severo')], default='BUENO', help_text='Vigor y estado general del cultivo', max_length=20),
        ),
    ]
