# Generated by Django 6.0.5 on 2026-10-06 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arroz', '0008_seguimientofenologico_estado_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocosto',
            name='aplicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costo_asociado', to='arroz.aplicacionagroquimico'),
        ),
        migrations.AddField(
            model_name='registrocosto',
            name='fertilizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costo_asociado', to='arroz.fertilizacion'),
        ),
        migrations.AddField(
            model_name='registrocosto',
            name='preparacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costo_asociado', to='arroz.preparacionmaquinaria'),
        ),
        migrations.AddField(
            model_name='registrocosto',
            name='riego',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costo_asociado', to='arroz.registrohidrico'),
        ),
    ]
